f = open('WCA_export_Competitions.tsv')
common_cities = {
    'Gdansk': 'Pomorskie',
    'Gdańsk': 'Pomorskie',
    'Poznań': 'Wielkopolskie',
    'Poznan': 'Wielkopolskie',
    'Lublin': 'Lubelskie',
    'Warszawa': 'Mazowieckie',
    'Kraków': 'Małopolskie',
    'Krakow': 'Małopolskie',
    'Dąbrowa Górnicza': 'Śląskie',
    'Dabrowa Gornicza': 'Śląskie',
    'Dabrowa Górnicza': 'Śląskie',
    'Rzeszów': 'Podkarpackie',
    'Rzeszow': 'Podkarpackie',
    'Łódź': 'Łódzkie',
    'Starogard Gdański': 'Pomorskie',
    'Starogard Gdanski': 'Pomorskie',
    'Grudziadz': 'Kujawsko-Pomorskie',
    'Grudziądz': 'Kujawsko-Pomorskie',
    'Warsaw': 'Mazowieckie',
    'Zawiercie': 'Śląskie',
    'Wrocław': 'Dolnośląskie',
    'Bełżyce': 'Lubelskie',
    'Szczecin': 'Zachodniopomorskie',
    'Szczecin ': 'Zachodniopomorskie',
    'Bielsko-Biała': 'Śląskie',
    'Krasnik': 'Lubelskie',
    'Kraśnik': 'Lubelskie',
    'Dębica': 'Podkarpackie',
    'Świdnik': 'Lubelskie',
    'Biała Podlaska': 'Lubelskie',
    'Siedlce': 'Mazowieckie',
    'Kędzierzyn-Koźle': 'Opolskie',
    'Opole': 'Opolskie',
    'Wroclaw': 'Dolnośląskie',
    'Mielec': 'Podkarpackie',
    'Olsztyn': 'Warmińsko-Mazurskie',
    'Wadowice': 'Małopolskie',
    'Będzin': 'Śląskie',
    'Białystok': 'Podlaskie',
    'Bialystok': 'Podlaskie',
    'Szczecinek': 'Zachodniopomorskie',
    'Byczyna': 'Opolskie',
    'Pawłowice': 'Śląskie',
    'Lodz': 'Łódzkie',
    'Częstochowa': 'Śląskie',
    'Czestochowa': 'Śląskie',
    'Gniezno': 'Wielkopolskie',
    'Płock': 'Mazowieckie',
    'Kaliska': 'Pomorskie',
    'Kielce': 'Świętokrzyskie',
    'Zamość': 'Lubelskie',
    'Pabianice': 'Łódzkie',
    'Jastrzębie-Zdrój': 'Śląskie',
    'Jastrzebie-Zdrój': 'Śląskie',
    'Pszczyna': 'Śląskie',
    'Rybnik': 'Śląskie',
    'Swierklany': 'Śląskie',
    'Gliwice': 'Śląskie',
    'Szczytno': 'Warmińsko-Mazurskie',
    'Bydgoszcz': 'Kujawsko-Pomorskie',
    'Lubartów': 'Lubelskie',
    'Domaniewice': 'Łódzkie',
    'Bełchatów': 'Łódzkie',
    'Chojnice': 'Pomorskie',
    'Koło': 'Wielkopolskie',
    'Białystok': 'Podlaskie',
    'Reda': 'Pomorskie',
    'Gdynia': 'Pomorskie',
    'Sopot': 'Pomorskie',
    'Biłgoraj': 'Lubelskie',
    'Łuków': 'Lubelskie',
    'Nowa Słupia': 'Świętokrzyskie',
    'Radom': 'Mazowieckie',
    'Rumia': 'Pomorskie',
    'Jastrzębie Zdrój': 'Śląskie',
    'Frydman': 'Małopolskie',
    'Żyrardów': 'Mazowieckie',
    'Sucha Beskidzka': 'Małopolskie',
    'Sieradz': 'Łódzkie',
    'Wojciechów': 'Lubelskie',
    'Gorlice': 'Małopolskie',
    'Jarosław': 'Podkarpackie',
    'Jasło': 'Podkarpackie',
    'Kluczbork': 'Opolskie',
    'Skierniewice': 'Lubelskie',
    'Wisła': 'Śląskie',
    'Środa Wielkopolska': 'Wielkopolskie',
    'Żuromin': 'Mazowieckie',
    'Olesno': 'Opolskie',
    'Człuchów': 'Pomorskie',
    'Ciechanów': 'Mazowieckie',
    'Konin': 'Wielkopolskie',
    'Tomaszów Mazowiecki': 'Łódzkie',
    'Giżycko': 'Warmińsko-Mazurskie',
    'Stalowa Wola': 'Podkarpackie',
    'Kęty': 'Małopolskie',
    'Korzenna': 'Małopolskie',
    'Elbląg': 'Warmińsko-Mazurskie',
    'Elblag': 'Warmińsko-Mazurskie',
    'Mikołajki': 'Warmińsko-Mazurskie',
    'Mysłowice': 'Śląskie',
    'Piotrków Trybunalski': 'Łódzkie',
    'Piła': 'Wielkopolskie',
    'Przeźmierowo': 'Wielkopolskie',
    'Radomsko': 'Łódzkie',
    'Dobrzeń Wielki': 'Opolskie',
    'Świdnica': 'Dolnośląskie',
    'Chorzów Batory': 'Śląskie',
    'Bielsko-Biala': 'Śląskie',
    'Chorzów': 'Śląskie',
    'Chorzow': 'Śląskie',
    'Sosnowiec': 'Śląskie',
    'Tarnowskie Gory': 'Śląskie',
    'Wodzisław Śląski': 'Śląskie',
    'Naprawa': 'Małopolskie',
    'Serokomla': 'Lubelskie',
    'Żmigród': 'Dolnośląskie',
    'Pilzno': 'Podkarpackie'
}
output_unsolved = open('export.csv', 'w', encoding = 'utf-8')
output_solved = open('export_solved.csv', 'w', encoding = 'utf-8')
for line in f:
    parts = line.split('\t')
    if parts[3] == "Poland":
        if parts[2] in common_cities:
            output_solved.write(f"{parts[0]},{parts[2]},{parts[10]},{parts[11]},{common_cities[parts[2]]}\n")
        else:
            output_unsolved.write(f"{parts[0]},{parts[2]},{parts[10]},{parts[11]}\n")
            
